### ISSUE TITLE
Add classifiers to setup.py to indicate Python support

### ISSUE THREAD

**Issue by svisser** [bmhatfield/python-pidfile#1]
This project doesn't pass this test here: http://caniusepython3.com/project/pidfile for Python 3.x support.

The project appears to work in Python 3.x (at least syntactically) so after some testing it should be possible to add PyPI classifiers in setup.py (to indicate supported Python versions). This should help those who wish to automatically find all dependencies that are / aren't yet compatible with Python 3.x.

**Comment by bmhatfield** [comment]
Done!

https://pypi.python.org/pypi/pidfile/0.1.1

Thank you again for this!
